class Extract:
    def __init__(self, extractor, extract_id, extract_dict=None):
        """Creates an extract

        Parameters
        ----------
        extractor : Extractor
            the extractor which created the extract
        extract_id : int
            the id of this extract to make it unique (made by the extractor)
        extract_dict : dict
            the dict of the extract state

        Returns
        -------
        Extract
            The created extract instance
        """

        self.id = extract_id
        self.extractor = extractor

        if extract_dict is None:
            self.speaker = None
            self.speaker_embeddings = None
            self.words = None
            self.start = None
            self.end = None
        else:
            self.speaker = extract_dict["speaker"]
            self.speaker_embeddings = [extract_dict["spk"]]
            self.words = extract_dict["result"]
            self.start = self.words[0]["start"]
            self.end = self.words[-1]["end"]

    def to_dict(self):
        """Turn the instance into a dict

        Returns
        -------
        dict
            a dictionnary with the current states of the instance
        """

        return {
            "id": self.id,
            "speaker": self.speaker.name,
            "speaker_embeddings": self.speaker_embeddings,
            "words": self.words,
            "start": self.start,
            "end": self.end,
        }

    @classmethod
    def from_dict(cls, data, extractor, speakers=None):
        """Create an extract with data state and the extractor

        Parameters
        ----------
        data : dict
            a dict with the states of the instance to create
        extractor : Extractor
            the extractor the extract was generated by
        speakers : dict
            dict linking speaker names to speakers
            if None then the extract speaker field is None

        Returns
        -------
        extract : Extract
            an extract with data states
        """

        if data["id"] >= extractor.next_id:
            raise ValueError("id is bigger than the extractor next id value")
        extract = cls(extractor, int(data["id"]))
        if speakers is not None:
            extract.speaker = speakers[data["speaker"]]
        extract.speaker_embeddings = data["speaker_embeddings"]
        extract.words = data["words"]
        extract.start = data["start"]
        extract.end = data["end"]
        return extract

    def append_text(self, extract):
        """append text of an extract to the extract

        Parameters
        ----------
        extract : Extract
            the extract with the text to append
        """

        self.words += extract.words
        self.end = extract.end
        if (
            self.speaker_embeddings is not None
            and extract.speaker_embeddings is not None
        ):
            self.speaker_embeddings += extract.speaker_embeddings
        elif self.speaker_embeddings is None:
            self.speaker_embeddings = extract.speaker_embeddings

    def split(self, at):
        """split the extract

        Parameters
        ----------
        at : int
            the index to split at

        Returns
        -------
        second : Extract
            the created extract form the split
        """

        # create new id
        second_id = self.extractor.next_id
        self.extractor.next_id += 1

        # create second
        second = Extract(self.extractor, second_id)
        second.words = self.words[at:]
        second.start = second.words[0]["start"]
        second.end = self.end

        # ajust this one
        self.words = self.words[:at]
        self.end = self.words[-1]["end"]
        self.speaker_embeddings = None
        return second

    def correct_text(self, corrections):
        """correct the text of an extract

        Parameters
        ----------
        corrections : list
            list of the corrections with the indexes to correct and the correction
        """

        # sort the correction according to their start
        corrections = sorted(corrections, key=lambda w: w[0][0])

        # offset becaause some words were removed
        offset = 0
        for word_range, correction in corrections:
            word_range[0] -= offset
            word_range[1] -= offset
            start = self.words[word_range[0]]["start"]
            end = self.words[word_range[1] - 1]["end"]
            for _ in range(word_range[0], word_range[1]):
                del self.words[word_range[0]]
            self.words.insert(
                word_range[0],
                {
                    "word": correction,
                    "start": start,
                    "end": end,
                },
            )
            offset += word_range[1] - word_range[0] - 1

    def timestamped_text(self):
        words_str = [
            f"{word['word']}({word['start']:.2f}-{word['end']:.2f})"
            for word in self.words
        ]
        return " ".join(words_str)

    def text(self):
        words_str = [word["word"] for word in self.words]
        return " ".join(words_str)

    def __str__(self):
        return self.extractor.extract_string(self)


class Extractor:
    def __init__(self):
        """Creates an extractor

        Returns
        -------
        Extractor
            The created extractor
        """

        self.next_id = 0
        self.string_format = {
            "timestamp": False,
            "word timestamp": False,
            "embedding": False,
            "id_num": False,
        }

    def to_dict(self):
        """saves the instance states in a dict

        Returns
        -------
        dict
            the states
        """

        return {"next_id": self.next_id, "string_format": self.string_format}

    @classmethod
    def from_dict(cls, data):
        """creates an extractor from data states

        Parameters
        ----------
        data : dict
            states of the extractor

        Returns
        -------
        extractor : Extractor
            an extractor with the data states
        """

        extractor = cls()
        extractor.next_id = data["next_id"]
        extractor.string_format = data["string_format"]
        return extractor

    def new_extract(self, extract_dict, time_offset=0.0):
        """creates an extract

        Parameters
        ----------
        extract_dict : dict
            states of the extract
        time_offset : float
            number of seconds to offset the timestamp

        Returns
        -------
        extract : Extract
            an extract with the extract_dict states
        """

        # offset the time
        if time_offset != 0.0:
            for word in extract_dict["result"]:
                word["start"] += time_offset
                word["end"] += time_offset

        # no speaker yet
        extract_dict["speaker"] = None

        # create it and add a new id
        extract = Extract(self, self.next_id, extract_dict)
        self.next_id += 1
        return extract

    def set_id_format(self, activate):
        self.string_format["id_num"] = activate

    def set_timestamp_format(self, activate):
        self.string_format["timestamp"] = activate

    def set_word_timestamp_format(self, activate):
        self.string_format["word timestamp"] = activate

    def stringify_extract_text(self, extract):
        if self.string_format["word timestamp"]:
            return extract.timestamped_text()
        else:
            return extract.text()

    def stringify_extract_speaker(self, extract):
        if extract.speaker is None:
            emb = extract.speaker_embeddings[0]
            if emb is None:
                return "[None]"
            return f"[{emb[0]:2f}, ..., {emb[0]:2f}]"
        else:
            return extract.speaker.name

    def extract_string(self, extract):
        speaker_str = self.stringify_extract_speaker(extract)
        text_str = self.stringify_extract_text(extract)

        id_str = ""
        if self.string_format["id_num"]:
            id_str = f"({extract.id:06d})"

        timestamp_str = ""
        if self.string_format["timestamp"]:
            timestamp_str = f"{{{extract.start:.2f}-{extract.end:.2f}}}"

        return f"{id_str}[{speaker_str}]{timestamp_str} : {text_str}"
