name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mlops-repo/mlops-app:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mlops-repo/mlops-app:${{ github.sha }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mlops-app \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/mlops-repo/mlops-app:${{ github.sha }} \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated
